- name: Upgrade Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars:
    ansible_command_timeout: 900
    initial_version: ''
  vars_files:
  - vars/main.yml
  - vars/vault.yml
  tasks:

  - name: Backup current configuration
    nxos_config:
      backup: yes
