- name: Upgrade Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars:
    ansible_command_timeout: 900
    initial_version: ''
  vars_files:
  - vars/main.yml
  - vars/vault.yml
  tasks:

  - name: Set fallback version
    set_stats:
      data:
        download_destination: "{{initial_image}}"
    when: result_ping.packet_loss != "0.00%"


