- name: Upgrade Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars_files:
  - vars/main.yml
  - vars/vault.yml
  tasks:
 
  # e.g. copy scp://root@172.16.1.45/nxos.10.2.5.bin bootflash: vrf management
  - name: Download image from SCP server
    vars:
      ansible_command_timeout: 3600
    nxos_command:
      commands:
      - command: "copy {{download_source}} {{download_destination}} vrf management"
        prompt:
        - 'Warning: There is already a file existing with this name. Do you want to overwrite (y/n)?[n]'
        - "{{download_server.user}}@{{download_server.host}}'s password:"
        answer:
        - y
        - "{{scp_server_password}}"
    register: result
  - name: Debug download image from SCP server
    debug:
      var: result
 
  # - name: Check File is there
  #   nxos_command:
  #     commands:
  #     - "copy running-config startup-config"
  #   register: result
  # - name: Debug
  #   debug:
  #     var: result
  
  # copy running-config startup-config 
  - name: Save running config into startup config
    nxos_command:
      commands:
        command: "copy running-config startup-config"
        wait_for: 'Copy complete.'
    register: result
  - name: Debug save running config into startup config
    debug:
      var: result

  # reload
  - name: Reload NXOS
    nxos_command:
      commands:
      - command: reload
        prompt: 'This command will reboot the system. (y/n)?'
        answer: "{{scp_server_password}}"
  
  - name: Wait for NXOS to come up
    ansible.builtin.wait_for_connection:
      timeout: 3600
      delay: 60
      sleep: 10




#nxos_command

# copy running-config startup-config

# reload

#  - name: Dowload new image from SCP download_server
#    nxos_config:

#nxos_config
# boot nxos bootflash:nxos.9.3.6.bin

# boot nxos bootflash:/nxos.10.3.6.bin