- name: Upgrade Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars_files:
  - vars/main.yml
  - vars/vault.yml
  tasks:
 
  - name: Debug command
    debug:
      msg: "copy {{download_source}} {{download_destination}} vrf management"

  # e.g. copy scp://root@172.16.1.45/nxos.10.2.5.bin bootflash: vrf management
  - name: Download image from scp server
    vars:
      ansible_command_timeout: 3600
    nxos_command:
      commands:
#      - command: "copy {{download_source}} {{download_destination}} vrf management"
      - command: "copy bootflash:poap_retry_debugs.log bootflash:poap_retry_debugs.log2"
        prompt:
        - 'Warning: There is already a file existing with this name. Do you want to overwrite (y/n)?[n]'
        - "{{download_server.user}}@{{download_server.host}}'s password:"
        answer:
        - y
        - "{{scp_server_password}}"
    register: result
  - name: Debug download image from SCP server
    debug:
      var: result
 
  - name: Check whether image file is there
    nxos_command:
      commands:
      - "dir"
    register: result
  - name: Debug
    debug:
      var: result
  - name: Assert that file is there
    that: "{{download_server.file}} in result.stdout"

  # boot nxos bootflash:nxos.9.3.6.bin
  - name: Set the new image as boot config
    nxos_config:
      lines: "boot nxos {{download_destination}}{{download_server.file}}"

  # copy running-config startup-config 
  - name: Save running config into startup config
    nxos_command:
      commands:
        command: "copy running-config startup-config"
        wait_for: 'Copy complete.'
    register: result
  - name: Debug save running config into startup config
    debug:
      var: result

  # reload
  - name: Reload NXOS
    nxos_command:
      commands:
      - command: reload
        prompt: 'This command will reboot the system. (y/n)?'
        answer: "{{scp_server_password}}"
  
  - name: Wait for NXOS to come up
    ansible.builtin.wait_for_connection:
      timeout: 3600
      delay: 60
      sleep: 10
