- name: Upgrade Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars:
    ansible_command_timeout: 1800  
  vars_files:
  - vars/main.yml
  - vars/vault.yml
  tasks:

  - name: Check currently running version
    nxos_facts:
      gather_subset: all
    register: result_facts
  - name: Check upgrade is needed
    debug:
      msg:
      - "Current Version: {{ansible_net__os}}"
      - "New Version: {{new_version}}"
  - name: Asset that new version is different than old version
    assert: 
      that: "ansible_net__os != new_version"

  - name: Download image from scp server (copy {{download_source}} {{download_destination}} vrf management)
    # e.g. copy scp://root@172.16.1.45/root/nxos.10.2.5.bin bootflash: vrf management
    nxos_config:
      commands:
      - command: "copy {{download_source}} {{download_destination}} vrf management"
        prompt:
        - "Warning: There is already a file existing with this name. Do you want to overwrite (y/n)?[n]"
        - "{{download_server.user}}@{{download_server.host}}'s password:"
        answer:
        - 'y'
        - "{{scp_server_password}}"
    #no_log: true
    register: result_download
  - name: Debug download image from SCP server
    debug:
      var: result_download
 
  - name: Check whether image file is there
    nxos_command:
      commands:
      - "dir"
    register: result_dir
  - name: Debug
    debug:
      var: result_dir
  - name: Assert that file is there
    assert:
      that: "'{{download_server.file}}' in result_dir.stdout[0]"

  - name: Backup current configuration
    nxos_config:
      backup: yes

  - name: Set the new image as boot config (boot nxos {{download_destination}}{{download_server.file}})
    nxos_config:
      lines:
      - "boot nxos {{download_destination}}{{download_server.file}}"

  - name: Save running config into startup config (copy running-config startup-config)
    nxos_config:
      lines:
      - copy running-config startup-config

  - name: Reload NXOS
    nxos_command:
      commands:
      - command: reload
        prompt: 'This command will reboot the system. (y/n)?'
        answer: "{{scp_server_password}}"
  
  - name: Wait for NXOS to come up
    wait_for_connection:
      timeout: 1800
      delay: 60
      sleep: 10

  - name: Smoke test (ping SCP server)
    ios_ping:
      dest: "{{download_server.host}}"

  - name: Check currently running version
    nxos_facts:
      gather_subset: all
    register: result_facts
  - name: Debug
    debug:
      var: result_facts
